const { generateFullReport } = require("./full-report.js");

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function reportToHtml(report) {
  const companyRows = (report.companyWiseSalaries || [])
    .map(
      (company) => `
        <tr>
          <td>${escapeHtml(company.company)}</td>
          <td>${escapeHtml(company.range)}</td>
          <td>${escapeHtml(company.notes)}</td>
        </tr>
      `
    )
    .join("");

  const actionPlan = (report.actionPlan || [])
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");

  const redFlags = (report.redFlags || [])
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");

  const skills = (report.skillsToAdd || [])
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");

  return `
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">

<style>

body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  color: #222;
  background: #f5f7fb;
  margin: 0;
  padding: 30px;
}

.container {
  max-width: 850px;
  margin: auto;
  background: white;
  padding: 35px;
  border-radius: 14px;
}

h1 {
  color: #111;
}

h2 {
  margin-top: 30px;
  border-bottom: 1px solid #ddd;
  padding-bottom: 8px;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 15px;
}

th,
td {
  border: 1px solid #ddd;
  padding: 10px;
  text-align: left;
}

th {
  background: #f1f1f1;
}

.script {
  background: #f7f7f7;
  padding: 15px;
  border-radius: 8px;
  margin-bottom: 12px;
}

.footer {
  margin-top: 40px;
  color: #777;
  font-size: 13px;
}

</style>

</head>

<body>

<div class="container">

<h1>NegotiateAI — Full Salary Negotiation Report</h1>

<h2>Company Salary Comparison</h2>

<table>

<thead>
<tr>
<th>Company</th>
<th>Estimated Range</th>
<th>Notes</th>
</tr>
</thead>

<tbody>

${companyRows}

</tbody>

</table>

<h2>Negotiation Script</h2>

<div class="script">
<strong>Opening:</strong>
<br>
${escapeHtml(report.negotiationScript?.opening)}
</div>

<div class="script">
<strong>When HR Asks Salary:</strong>
<br>
${escapeHtml(report.negotiationScript?.whenAsked)}
</div>

<div class="script">
<strong>Counter Offer:</strong>
<br>
${escapeHtml(report.negotiationScript?.counterOffer)}
</div>

<div class="script">
<strong>Closing:</strong>
<br>
${escapeHtml(report.negotiationScript?.closing)}
</div>

<h2>Offer Evaluation</h2>

<p>
${escapeHtml(report.offerEvaluation)}
</p>

<h2>Action Plan</h2>

<ul>
${actionPlan}
</ul>

<h2>Potential Red Flags</h2>

<ul>
${redFlags}
</ul>

<h2>Skills To Add</h2>

<ul>
${skills}
</ul>

<div class="footer">

Generated by NegotiateAI.

This report provides AI-generated career and salary guidance and should be used as an informational tool.

</div>

</div>

</body>

</html>
`;
}


module.exports = async function handler(req, res) {

  // --------------------------------
  // 1. Check request method
  // --------------------------------

  if (req.method !== "POST") {

    return res.status(405).json({
      success: false,
      message: "Method not allowed"
    });

  }


  try {

    // --------------------------------
    // 2. Read request
    // --------------------------------

    const {
      paymentId,
      adminSecret
    } = req.body || {};


    if (!paymentId || !adminSecret) {

      return res.status(400).json({
        success: false,
        message:
          "Payment ID and admin secret are required"
      });

    }


    // --------------------------------
    // 3. Verify admin
    // --------------------------------

    if (
      adminSecret !==
      process.env.ADMIN_SECRET
    ) {

      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });

    }


    // --------------------------------
    // 4. Get payment from Redis
    // --------------------------------

    const getResponse = await fetch(
      `${process.env.KV_REST_API_URL}/get/payment:${encodeURIComponent(paymentId)}`,
      {
        method: "GET",

        headers: {
          Authorization:
            `Bearer ${process.env.KV_REST_API_TOKEN}`
        }
      }
    );


    if (!getResponse.ok) {

      throw new Error(
        "Failed to access payment database"
      );

    }


    const paymentData =
      await getResponse.json();


    if (
      paymentData.result === null ||
      paymentData.result === undefined
    ) {

      return res.status(404).json({
        success: false,
        message: "Payment not found"
      });

    }


    // --------------------------------
    // 5. Parse Redis response
    // --------------------------------
    //
    // Actual structure:
    //
    // result
    //   ↓
    // JSON wrapper
    //   ↓
    // value
    //   ↓
    // JSON payment object
    //

    let redisWrapper =
      paymentData.result;


    if (
      typeof redisWrapper === "string"
    ) {

      redisWrapper =
        JSON.parse(redisWrapper);

    }


    let payment =
      redisWrapper.value;


    if (
      typeof payment === "string"
    ) {

      payment =
        JSON.parse(payment);

    }


    if (!payment) {

      return res.status(404).json({
        success: false,
        message:
          "Payment data is empty"
      });

    }


    console.log(
      "Payment retrieved:",
      {
        paymentId:
          payment.paymentId,

        status:
          payment.status,

        email:
          payment.email
      }
    );


    // --------------------------------
    // 6. Check payment status
    // --------------------------------

    if (
      payment.status !==
      "PAYMENT_SUBMITTED"
    ) {

      return res.status(400).json({

        success: false,

        message:
          `Payment status is ${payment.status}`

      });

    }


    // --------------------------------
    // 7. Generate AI report
    // --------------------------------

    console.log(
      `Generating report for ${paymentId}`
    );


    const report =
      await generateFullReport(
        payment.profile || {}
      );


    if (!report) {

      throw new Error(
        "AI report generation returned empty result"
      );

    }


    console.log(
      `Report generated for ${paymentId}`
    );


    // --------------------------------
    // 8. Save generated report
    // --------------------------------

    const reportRecord = {

      paymentId,

      email:
        payment.email,

      profile:
        payment.profile || {},

      report,

      generatedAt:
        new Date().toISOString()

    };


    const reportSaveResponse =
      await fetch(
        `${process.env.KV_REST_API_URL}/set/report:${encodeURIComponent(paymentId)}`,

        {

          method: "POST",

          headers: {

            Authorization:
              `Bearer ${process.env.KV_REST_API_TOKEN}`,

            "Content-Type":
              "application/json"

          },

          body: JSON.stringify({

            value:
              JSON.stringify(reportRecord)

          })

        }
      );


    if (!reportSaveResponse.ok) {

      throw new Error(
        "Failed to save generated report"
      );

    }


    // --------------------------------
    // 9. Update payment status
    // --------------------------------

    payment.status =
      "VERIFIED";


    payment.verifiedAt =
      new Date().toISOString();


    payment.reportKey =
      `report:${paymentId}`;


    const paymentSaveResponse =
      await fetch(

        `${process.env.KV_REST_API_URL}/set/payment:${encodeURIComponent(paymentId)}`,

        {

          method: "POST",

          headers: {

            Authorization:
              `Bearer ${process.env.KV_REST_API_TOKEN}`,

            "Content-Type":
              "application/json"

          },

          body: JSON.stringify({

            value:
              JSON.stringify(payment)

          })

        }

      );


    if (!paymentSaveResponse.ok) {

      throw new Error(
        "Failed to update payment status"
      );

    }


    console.log(
      `Payment ${paymentId} marked as VERIFIED`
    );


    // --------------------------------
    // 10. Generate email HTML
    // --------------------------------

    const emailHtml =
      reportToHtml(report);


    // --------------------------------
    // 11. Send email through Resend
    // --------------------------------

    let emailSent = false;


    if (
      process.env.RESEND_API_KEY &&
      payment.email
    ) {

      const emailResponse =
        await fetch(
          "https://api.resend.com/emails",

          {

            method: "POST",

            headers: {

              Authorization:
                `Bearer ${process.env.RESEND_API_KEY}`,

              "Content-Type":
                "application/json"

            },

            body: JSON.stringify({

              from:
                process.env.EMAIL_FROM ||
                "NegotiateAI <onboarding@resend.dev>",

              to: [
                "24981a05p5@raghuenggcollege.in"
              ],

              subject:
                "Your NegotiateAI Full Report is Ready",

              html:
                emailHtml

            })

          }
        );


      if (!emailResponse.ok) {

        const errorText =
          await emailResponse.text();


        console.error(
          "Resend error:",
          errorText
        );

      } else {

        emailSent = true;

        console.log(
          `Report email sent to ${payment.email}`
        );

      }

    }


    // --------------------------------
    // 12. Return success
    // --------------------------------

    return res.status(200).json({

      success: true,

      message:
        emailSent
          ? "Payment verified, report generated and customer notified"
          : "Payment verified and report generated",

      paymentId,

      emailSent

    });


  } catch (error) {

    console.error(
      "Send report error:",
      error
    );


    return res.status(500).json({

      success: false,

      message:
        "Failed to verify payment and generate report",

      error:
        error.message

    });

  }

};
